#!/bin/csh

#set files = `ls ../../examples/`

set COSTABSHOME = /home/tacas19/costabs/bin/saco
set ETHIRPATH = /home/tacas19/EthIR/ethir

set files = `ls /home/tacas19/Desktop/examples/subset/`
set names = `echo $files:q | sed 's/ /  /g'`


rm /home/tacas19/Desktop/examples/subset/*.disasm
rm /home/tacas19/Desktop/examples/subset/*.evm

                    
         python $ETHIRPATH/test/exe_several.py


