#!/bin/csh

set COSTABSHOME = /home/tacas19/costabs/bin/saco
set ETHIRPATH = /home/tacas19/EthIR/ethir
set size = ${#argv}

if ($size == 2) then
    set file_name = $argv[1]
    set contract_name = $argv[2]
    #set file_name = /home/tacas19/Desktop/examples/pot_tacas19.sol


    python $ETHIRPATH/oyente-ethir.py -s $file_name -saco -eop -cfg
    if (-e /tmp/costabs/$contract_name"_saco.rbr") then
	    python $ETHIRPATH/test/exec_contract_user.py $file_name $contract_name"_saco.rbr"
    else
	echo "ERROR: The solidity file does not contain the contract "$contract_name
    endif

else
    echo "Incorrect number of arguments."
    echo "The format required is ./gastap_contract /home/tacas19/Desktop/examples/pot_tacas19.sol EthereumPot"
    
endif
