#!/bin/csh

set files = `ls ../../examples/`
set names = `echo $files:q | sed 's/ /  /g'`

if (-e ./result.txt) then
    rm -f ./result.txt
endif


foreach contract ($names)
    set ext = `echo $contract:q | sed 's/\./  /g'`
    if $ext[2] == "sol" then
        set result = `python ./test.py "../../examples/"$contract""`
        set loops = `echo $result | cut -c 7-`

        if $loops != 0 then
            echo $contract" si" >> result.txt
            #It contains a loop -> It executes EthIR
            echo " "
            echo "Starting the decompilation of "$contract
            echo " "

            python ../oyente-ethir.py -s ../../examples/$contract -saco -eop

            #It takes the name of the contract without the extension
            set c_name = `echo $contract:q | sed 's/\./ /g'`
            set rbr_file = $c_name[1]"_saco.rbr"
            
            # if (-e /tmp/costabs/$rbr_file) then
            #     ${COSTABSHOME}/src/interfaces/shell/costabs /tmp/costabs/$rbr_file -entries block0 -cost_model gas -ethir yes -backend cofloco
            # else if (-e /tmp/costabs/rbr_saco.rbr) then
            #     ${COSTABSHOME}/src/interfaces/shell/costabs /tmp/costabs/rbr_saco.rbr -entries block0 -cost_model gas -ethir yes -backend cofloco

            # else if (-e /tmp/costabs/rbr1_saco.rbr && $words[3] == "AuctusEther.sol") then
            #     ${COSTABSHOME}/src/interfaces/shell/costabs /tmp/costabs/rbr1_saco.rbr -entries block0 -cost_model gas -ethir yes -backend cofloco

            # else if (-e /tmp/costabs/rbr0_saco.rbr) then
            #     ${COSTABSHOME}/src/interfaces/shell/costabs /tmp/costabs/rbr0_saco.rbr -entries block0 -cost_model gas -ethir yes -backend cofloco

            # else 
            #     echo "no2"
            #     echo $rbr_file

            # endif

        endif
    endif
end

